changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
      - duplicate
      - question
      - invalid
      - wontfix
    authors:
      - octocat  # Example bot user to exclude
  categories:
    - title: 🚀 Features
      labels:
        - feat
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - fix
        - bugfix
        - bug
    - title: 📚 Documentation
      labels:
        - docs
        - documentation
    - title: 🧪 Testing
      labels:
        - test
        - testing
    - title: 🔧 Maintenance
      labels:
        - chore
        - maintenance
        - refactor
    - title: ⚡ Performance
      labels:
        - perf
        - performance
    - title: 💄 Style
      labels:
        - style
        - ui
        - ux
    - title: 🏗️ Build System
      labels:
        - build
        - ci
        - cd
    - title: 🔥 Breaking Changes
      labels:
        - breaking
        - breaking-change
    - title: Other Changes
      labels:
        - "*"