name: 'Setup Android Environment'
description: 'Set up JDK, cache Gradle dependencies, and prepare Android build environment'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-home-cache-cleanup: true
        cache-read-only: ${{ github.event_name == 'pull_request' }}

    - name: Cache Android SDK
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.ANDROID_SDK_ROOT }}
          ~/.android
        key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/build.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-android-sdk-

    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew