name: 'Build Android App'
description: 'Build Android APK/AAB (unsigned)'

inputs:
  build-type:
    description: 'Build type: debug or release'
    required: true
    default: 'debug'
  
  build-aab:
    description: 'Whether to build AAB bundle'
    required: false
    default: 'false'
    
  version-code:
    description: 'Version code for the build'
    required: false
    default: ''
    
  version-name:
    description: 'Version name for the build'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Cache build outputs
      uses: actions/cache@v4
      with:
        path: |
          app/build/intermediates
          app/build/tmp
          build/kotlin
        key: ${{ runner.os }}-build-${{ inputs.build-type }}-${{ hashFiles('**/src/**', '**/build.gradle.kts', '**/libs.versions.toml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ inputs.build-type }}-
          ${{ runner.os }}-build-

    - name: Enable Gradle build cache
      shell: bash
      run: |
        mkdir -p ~/.gradle
        echo "org.gradle.caching=true" >> ~/.gradle/gradle.properties
        echo "org.gradle.parallel=true" >> ~/.gradle/gradle.properties
        echo "org.gradle.configureondemand=true" >> ~/.gradle/gradle.properties
        echo "org.gradle.daemon=true" >> ~/.gradle/gradle.properties

    - name: Run tests
      shell: bash
      run: ./gradlew test --build-cache

    - name: Build APK
      shell: bash
      run: |
        # Verify keystore configuration
        echo "Checking keystore setup..."
        if [[ -f "app/debug.keystore" ]]; then
          echo "✅ Found committed debug.keystore"
          ls -la app/debug.keystore
        else
          echo "❌ Missing app/debug.keystore - builds will have inconsistent signatures"
        fi
        
        # Check if gradle will use default Android SDK keystore
        if [[ -f "$HOME/.android/debug.keystore" ]]; then
          echo "⚠️  Found default Android SDK keystore - may conflict with committed keystore"
          ls -la "$HOME/.android/debug.keystore"
        fi
        
        if [[ -n "${{ inputs.version-code }}" && -n "${{ inputs.version-name }}" ]]; then
          ./gradlew assemble${{ inputs.build-type }} --build-cache \
            -PversionCode=${{ inputs.version-code }} \
            -PversionName=${{ inputs.version-name }}
        else
          ./gradlew assemble${{ inputs.build-type }} --build-cache
        fi

    - name: Build AAB
      if: inputs.build-aab == 'true'
      shell: bash
      run: |
        if [[ -n "${{ inputs.version-code }}" && -n "${{ inputs.version-name }}" ]]; then
          ./gradlew bundle${{ inputs.build-type }} --build-cache \
            -PversionCode=${{ inputs.version-code }} \
            -PversionName=${{ inputs.version-name }}
        else
          ./gradlew bundle${{ inputs.build-type }} --build-cache
        fi