name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  # ==============================================================================
  # Automated Security Updates
  # ==============================================================================
  security-updates:
    name: Security Updates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Check for security vulnerabilities
        id: audit
        run: |
          # Run security audit and capture output
          npm audit --audit-level=moderate --json > audit-results.json || true

          # Check if there are any vulnerabilities
          VULN_COUNT=$(cat audit-results.json | jq '.metadata.vulnerabilities.total // 0')
          echo "vulnerabilities=${VULN_COUNT}" >> $GITHUB_OUTPUT

          if [ "$VULN_COUNT" -gt 0 ]; then
            echo "Found $VULN_COUNT vulnerabilities"
            cat audit-results.json | jq '.advisories'
          else
            echo "No security vulnerabilities found"
          fi

      - name: Apply security fixes
        if: steps.audit.outputs.vulnerabilities > 0
        run: |
          # Try to fix vulnerabilities automatically
          npm audit fix --audit-level=moderate

          # Check if package-lock.json was modified
          if git diff --quiet package-lock.json; then
            echo "No changes made to package-lock.json"
          else
            echo "package-lock.json was updated with security fixes"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.audit.outputs.vulnerabilities > 0
        run: |
          # Configure git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Create and switch to new branch
          git checkout -b security-updates-$(date +%s)
          
          # Add and commit changes
          git add package-lock.json package.json
          git commit -m "fix(deps): apply security updates
          
          Automated security fixes for npm dependencies.
          
          Vulnerabilities fixed: ${{ steps.audit.outputs.vulnerabilities }}
          
          Auto-generated by: GitHub Actions"
          
          # Push branch
          git push origin HEAD
          
          # Create PR using GitHub CLI
          gh pr create \
            --title "🔒 Security Updates - Automated Dependency Fixes" \
            --body "## Automated Security Updates

          This PR contains automated security fixes for npm dependencies.

          **Changes:**
          - Applied \`npm audit fix\` to resolve security vulnerabilities  
          - Updated package-lock.json with secure versions

          **Vulnerabilities Fixed:** ${{ steps.audit.outputs.vulnerabilities }}

          **Review Notes:**
          - ✅ All changes are security-related dependency updates
          - ✅ No breaking changes expected
          - ✅ CI will validate the changes

          **Auto-generated by:** [Dependency Update Workflow](.github/workflows/dependency-update.yml)" \
            --label security,dependencies,automated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # ==============================================================================
  # React Native Updates Check
  # ==============================================================================
  react-native-updates:
    name: React Native Updates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Check React Native updates
        id: rn-check
        run: |
          # Get current React Native version
          CURRENT_RN=$(node -p "require('./package.json').dependencies['react-native']")
          echo "current_version=${CURRENT_RN}" >> $GITHUB_OUTPUT

          # Check latest stable version
          LATEST_RN=$(npm view react-native version)
          echo "latest_version=${LATEST_RN}" >> $GITHUB_OUTPUT

          echo "Current React Native: ${CURRENT_RN}"
          echo "Latest React Native: ${LATEST_RN}"

          # Compare versions (basic check)
          if [ "${CURRENT_RN}" != "${LATEST_RN}" ]; then
            echo "update_available=true" >> $GITHUB_OUTPUT
            echo "📱 React Native update available: ${CURRENT_RN} → ${LATEST_RN}"
          else
            echo "update_available=false" >> $GITHUB_OUTPUT
            echo "✅ React Native is up to date"
          fi

      - name: Create React Native update issue
        if: steps.rn-check.outputs.update_available == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const title = `📱 React Native Update Available: ${context.payload.inputs?.current_version || 'current'} → ${{ steps.rn-check.outputs.latest_version }}`;
            const body = `## React Native Update Available

            A new version of React Native is available:

            - **Current version:** \`${{ steps.rn-check.outputs.current_version }}\`
            - **Latest version:** \`${{ steps.rn-check.outputs.latest_version }}\`

            ### Update Checklist

            - [ ] Review [React Native changelog](https://github.com/facebook/react-native/releases)
            - [ ] Check for breaking changes
            - [ ] Update React Native: \`npx react-native upgrade\`
            - [ ] Update related dependencies (React, Metro, etc.)
            - [ ] Test Android build
            - [ ] Test iOS build  
            - [ ] Update documentation if needed
            - [ ] Run full test suite

            ### Resources

            - [React Native Upgrade Guide](https://react-native-community.github.io/upgrade-helper/)
            - [Breaking Changes](https://github.com/facebook/react-native/wiki/Breaking-Changes)

            ---
            *Auto-generated by [Dependency Update Workflow](.github/workflows/dependency-update.yml)*`;

            // Check if issue already exists
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['react-native', 'update'],
              state: 'open'
            });

            if (issues.data.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['react-native', 'update', 'enhancement']
              });
              console.log('Created React Native update issue');
            } else {
              console.log('React Native update issue already exists');
            }
